# parameters for emergency pull-over plug-in
vehicleID: "default_id"            
lane_change_desired_steps: 1    
maxCrosstrackError: 2.0
time_step: 15.0
lane_change_speed_adjustment: 0.7 
maxLaneChangeDist: 22.0
stopping_deceleration: 2.5
lane_change_recheck_time: 1.5