timeHeadway: 3.5
standStillHeadway: 22.0
maxAccel: 1.5
Kp: 0.4
Kd: 0.0 #0.1
Ki: 0.03 #0.035
maxValue: 2.0
minValue: -10.0
cmdTmestamp: 100
adjustmentCap: 20.0
dt: 0.1
integratorMax: 30
integratorMin: -30
wheelBase: 2.84
lowpassGain: 0.5 #1.0
lookaheadRatio: 1.5 #1.5
minLookaheadDist: 30.0 #15
correctionAngle: 0.00 #-0.022 to turn right
integratorMax_pp: 0.1
integratorMin_pp: -0.1
Ki_pp: 0.012